/** Tailwind / CSS class bundles for LinkHelp premium app theme */
export const premium = {
  appPage: 'lh-app-page px-5 py-5 sm:px-6 sm:py-6',
  glassCard: 'lh-glass-card',
  glassCardSolid: 'lh-glass-card-solid',
  glassCardPadded: 'lh-glass-card p-4 sm:p-5',
  glassCardSolidPadded: 'lh-glass-card-solid p-4 sm:p-5',
  btnPrimary: 'lh-btn-primary',
  btnSecondary: 'lh-btn-secondary',
  badge: 'lh-badge',
  sectionTitle: 'lh-section-title',
  sectionSubtitle: 'lh-section-subtitle',
  input: 'lh-input',
  modalOverlay: 'lh-modal-overlay',
  modalPanel: 'lh-modal-panel max-w-2xl',
  modalPanelLg: 'lh-modal-panel max-w-5xl',
  modalHeader: 'lh-modal-header',
  modalBody: 'lh-modal-body',
  modalFooter: 'lh-modal-footer',
  sidebar: 'lh-sidebar',
  textMuted: 'lh-text-muted',
  textHeading: 'lh-text-heading',
  iconChip: 'lh-icon-chip',
} as const;
