import { useEffect, useState, type ReactNode } from 'react';
import { MotionConfig, motion, useReducedMotion } from 'motion/react';
import { ArrowRight, BadgeCheck, Check, ChevronDown, Clock3, Coins, MapPin, Menu, ShieldCheck, Sparkles, Star, UsersRound, WalletCards, X } from 'lucide-react';
import { Logo } from '@/components/ui/Logo';
import { ByFluxBadge } from '@/components/brand/ByFluxBadge';
import { WaitlistForm } from './WaitlistForm';
import { faqs, helperBadges, landingServices } from './landingData';

const ease = [0.22, 1, 0.36, 1] as const;
const reveal = { initial: { opacity: 0, y: 24 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: '-70px' }, transition: { duration: 0.65, ease } };

function LandingSeo() {
  useEffect(() => {
    const title = 'Link Help Québec | La liste d’attente est ouverte';
    const description = 'Trouvez un coup de main local ou offrez vos services au Québec. Rejoignez gratuitement la liste d’attente de Link Help.';
    const previousTitle = document.title;
    document.title = title;
    document.documentElement.lang = 'fr-CA';
    const entries: [string, string, string][] = [['name', 'description', description], ['property', 'og:title', title], ['property', 'og:description', description], ['property', 'og:type', 'website'], ['property', 'og:url', 'https://www.linkhelp.app/'], ['property', 'og:image', 'https://www.linkhelp.app/brand/linkhelp-app-source.png'], ['name', 'twitter:card', 'summary_large_image']];
    const created: HTMLElement[] = [];
    for (const [attribute, key, value] of entries) {
      let node = document.head.querySelector(`meta[${attribute}="${key}"]`) as HTMLMetaElement | null;
      if (!node) { node = document.createElement('meta'); node.setAttribute(attribute, key); document.head.appendChild(node); created.push(node); }
      node.content = value;
    }
    const json = document.createElement('script');
    json.type = 'application/ld+json';
    json.textContent = JSON.stringify({ '@context': 'https://schema.org', '@type': 'WebSite', name: 'Link Help', url: 'https://www.linkhelp.app/', inLanguage: 'fr-CA', description });
    document.head.appendChild(json);
    return () => { document.title = previousTitle; created.forEach((node) => node.remove()); json.remove(); };
  }, []);
  return null;
}

function Section({ id, eyebrow, title, intro, children, className = '', dark = false }: { id?: string; eyebrow?: string; title: string; intro?: string; children: ReactNode; className?: string; dark?: boolean }) {
  return <section id={id} className={`scroll-mt-24 px-5 py-20 sm:px-8 sm:py-28 ${className}`}><div className="mx-auto max-w-7xl"><motion.div {...reveal} className="mb-12 max-w-3xl sm:mb-16">{eyebrow && <p className={`text-xs font-bold uppercase tracking-[.22em] ${dark ? 'text-[#7eb3ff]' : 'text-[#0866ff]'}`}>{eyebrow}</p>}<h2 className={`mt-4 text-balance text-3xl font-bold leading-[1.08] tracking-[-.045em] sm:text-5xl ${dark ? 'text-white' : 'text-[#0a1830]'}`}>{title}</h2>{intro && <p className={`mt-5 max-w-2xl text-base leading-7 sm:text-lg ${dark ? 'text-white/65' : 'text-[#5e6d82]'}`}>{intro}</p>}</motion.div>{children}</div></section>;
}

function LandingNavbar() {
  const [open, setOpen] = useState(false);
  const links = [['#fonctionnement', 'Fonctionnement'], ['#clients', 'Clients'], ['#helpers', 'Helpers'], ['#faq', 'FAQ']] as const;
  return <header className="sticky top-0 z-50 border-b border-white/70 bg-white/80 backdrop-blur-2xl"><nav aria-label="Navigation principale" className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 sm:px-8"><a href="#accueil" aria-label="Link Help — accueil" className="rounded-lg focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#0866ff]/20"><Logo className="h-9 w-auto" /></a><div className="hidden items-center gap-8 lg:flex">{links.map(([href, label]) => <a key={href} href={href} className="text-sm font-semibold text-[#536277] transition hover:text-[#0866ff] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#0866ff]/15">{label}</a>)}</div><a href="#liste" className="hidden min-h-11 items-center rounded-full bg-[#0866ff] px-5 text-sm font-bold text-white shadow-[0_12px_28px_rgba(8,102,255,.22)] transition hover:-translate-y-0.5 lg:inline-flex">Accès prioritaire</a><button type="button" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="landing-mobile-menu" aria-label={open ? 'Fermer le menu' : 'Ouvrir le menu'} className="flex h-11 w-11 items-center justify-center rounded-full border border-[#dce7f3] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#0866ff]/20 lg:hidden">{open ? <X /> : <Menu />}</button></nav>{open && <motion.div id="landing-mobile-menu" initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} className="border-t border-[#e6edf5] bg-white px-5 pb-5 lg:hidden">{links.map(([href, label]) => <a key={href} href={href} onClick={() => setOpen(false)} className="block border-b border-[#edf2f7] py-4 text-sm font-semibold text-[#314159]">{label}</a>)}<a href="#liste" onClick={() => setOpen(false)} className="mt-5 flex min-h-12 items-center justify-center rounded-full bg-[#0866ff] text-sm font-bold text-white">Rejoindre la liste</a></motion.div>}</header>;
}

function ProductPreview() {
  return <div className="relative mx-auto max-w-[34rem] lg:ml-auto"><div className="absolute -inset-10 rounded-full bg-[radial-gradient(circle,#bdd9ff_0%,rgba(220,236,255,.6)_45%,transparent_72%)] blur-2xl" /><motion.div animate={{ y: [0, -7, 0] }} transition={{ duration: 7, repeat: Infinity, ease: 'easeInOut' }} className="relative rounded-[2.4rem] border border-white/90 bg-white/85 p-3 shadow-[0_45px_120px_rgba(25,65,118,.2)] backdrop-blur-xl"><div className="overflow-hidden rounded-[1.9rem] bg-[#f3f7fc] p-5 sm:p-6"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-semibold text-[#728198]">Aperçu de l’expérience</p><p className="mt-1 text-lg font-bold">De quoi avez-vous besoin?</p></div><img src="/assets/characters/max-quebec/thumbs-up-bust.png" alt="Max Québec, mascotte de Link Help" className="h-20 w-20 object-contain" loading="eager" /></div><div className="mt-4 rounded-[1.4rem] bg-[linear-gradient(135deg,#0866ff,#0648aa)] p-5 text-white shadow-[0_20px_45px_rgba(8,102,255,.22)]"><p className="flex items-center gap-2 text-xs font-semibold text-white/70"><MapPin className="h-4 w-4" /> Près de chez vous</p><p className="mt-3 text-xl font-bold">Des helpers locaux, quand ça compte.</p><div className="mt-5 flex flex-wrap gap-2"><span className="rounded-full bg-white/15 px-3 py-2 text-xs">Ménage</span><span className="rounded-full bg-white/15 px-3 py-2 text-xs">Assemblage</span></div></div><div className="mt-3 grid grid-cols-2 gap-3"><div className="rounded-[1.25rem] bg-white p-4 shadow-sm"><UsersRound className="h-5 w-5 text-[#0866ff]" /><p className="mt-7 text-sm font-bold">Helpers locaux</p><p className="mt-1 text-xs text-[#728198]">Profils clairs</p></div><div className="rounded-[1.25rem] bg-white p-4 shadow-sm"><Clock3 className="h-5 w-5 text-[#0866ff]" /><p className="mt-7 text-sm font-bold">Simple et rapide</p><p className="mt-1 text-xs text-[#728198]">En quelques étapes</p></div></div></div></motion.div><div className="absolute -bottom-7 -left-2 rounded-2xl border border-white bg-white/90 p-4 shadow-[0_20px_50px_rgba(29,74,126,.16)] backdrop-blur-xl sm:-left-8"><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#eaf3ff] text-[#0866ff]"><ShieldCheck className="h-5 w-5" /></span><div><p className="text-xs font-bold">Pensé pour la confiance</p><p className="text-[11px] text-[#728198]">Une expérience claire</p></div></div></div></div>;
}

export function LandingPagePremium() {
  const reduceMotion = useReducedMotion();
  const scrollToForm = () => { const input = document.querySelector('#liste input') as HTMLInputElement | null; input?.scrollIntoView({ behavior: reduceMotion ? 'auto' : 'smooth', block: 'center' }); window.setTimeout(() => input?.focus({ preventScroll: true }), reduceMotion ? 0 : 500); };
  return <MotionConfig reducedMotion="user"><div className="min-h-screen overflow-x-hidden bg-white font-sans text-[#0b1930]"><LandingSeo /><LandingNavbar /><main>
    <section id="accueil" className="relative isolate overflow-hidden px-5 pb-24 pt-14 sm:px-8 sm:pb-32 sm:pt-20"><div className="absolute inset-0 -z-20 bg-[linear-gradient(180deg,#f7fbff_0%,#fff_88%)]" /><div className="absolute left-1/2 top-[-18rem] -z-10 h-[44rem] w-[64rem] -translate-x-1/2 rounded-full bg-[radial-gradient(circle,rgba(78,145,255,.2),transparent_70%)] blur-2xl" /><div className="mx-auto grid max-w-7xl items-center gap-16 lg:min-h-[42rem] lg:grid-cols-[1.03fr_.97fr]"><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .75, ease }}><span className="inline-flex items-center gap-2 rounded-full border border-[#cfe0f4] bg-white/80 px-3.5 py-2 text-xs font-bold text-[#0866ff] shadow-sm backdrop-blur"><Sparkles className="h-3.5 w-3.5" /> Bientôt au Québec</span><h1 className="mt-7 max-w-3xl text-balance text-[2.9rem] font-bold leading-[.98] tracking-[-.06em] sm:text-6xl lg:text-[4.65rem]">L’aide locale, <span className="bg-[linear-gradient(110deg,#0866ff,#0047b9)] bg-clip-text text-transparent">simplement humaine.</span></h1><p className="mt-7 max-w-xl text-lg leading-8 text-[#53647a] sm:text-xl">Link Help connecte les personnes qui ont besoin d’un coup de main avec des helpers de leur communauté — clairement, localement et au bon moment.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><button onClick={scrollToForm} className="inline-flex min-h-13 items-center justify-center gap-2 rounded-full bg-[#0866ff] px-7 text-sm font-bold text-white shadow-[0_18px_38px_rgba(8,102,255,.25)] transition hover:-translate-y-0.5">Rejoindre la liste <ArrowRight className="h-4 w-4" /></button><a href="#fonctionnement" className="inline-flex min-h-13 items-center justify-center rounded-full border border-[#d4e0ed] bg-white/80 px-7 text-sm font-bold text-[#25364d] shadow-sm backdrop-blur">Découvrir Link Help</a></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-[#65758a]">{['Gratuit', 'Aucun engagement', 'Accès prioritaire'].map((item) => <span key={item} className="inline-flex items-center gap-2"><span className="flex h-5 w-5 items-center justify-center rounded-full bg-[#eaf3ff]"><Check className="h-3.5 w-3.5 text-[#0866ff]" /></span>{item}</span>)}</div></motion.div><motion.div initial={{ opacity: 0, x: 28 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .85, delay: .1, ease }}><ProductPreview /></motion.div></div></section>

    <section id="liste" className="scroll-mt-24 px-5 py-10 sm:px-8 sm:py-14"><div className="mx-auto grid max-w-7xl items-center gap-10 overflow-hidden rounded-[2.25rem] border border-[#dce8f5] bg-[linear-gradient(135deg,#f7fbff,#edf5ff)] p-6 shadow-[0_30px_90px_rgba(32,66,103,.08)] sm:p-10 lg:grid-cols-[.82fr_1.18fr] lg:p-14"><motion.div {...reveal}><p className="text-xs font-bold uppercase tracking-[.22em] text-[#0866ff]">Soyez parmi les premiers</p><h2 className="mt-4 text-balance text-3xl font-bold leading-[1.08] tracking-[-.045em] sm:text-5xl">Votre ville peut être la prochaine.</h2><p className="mt-5 max-w-lg text-lg leading-8 text-[#5e6d82]">Votre inscription guide directement notre prélancement au Québec.</p><p className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#35465d]"><ShieldCheck className="h-5 w-5 text-[#0866ff]" /> Vos renseignements servent uniquement au prélancement.</p></motion.div><motion.div {...reveal}><WaitlistForm /></motion.div></div></section>

    <Section id="fonctionnement" eyebrow="Comment ça fonctionne" title="Un besoin. Des personnes locales. Un choix éclairé." intro="Un parcours court, sans recherches interminables."><div className="grid gap-4 md:grid-cols-3">{[['01', 'Publiez votre demande', 'Décrivez votre besoin, votre secteur et le moment qui vous convient.'], ['02', 'Découvrez les helpers', 'Consultez les profils et les éléments de réputation disponibles.'], ['03', 'Choisissez sereinement', 'Échangez et retenez la personne qui correspond à votre besoin.']].map(([number, title, body], index) => <motion.article key={number} {...reveal} className={`rounded-[1.75rem] border p-7 transition hover:-translate-y-1 ${index === 1 ? 'border-[#0866ff] bg-[#0866ff] text-white shadow-[0_24px_60px_rgba(8,102,255,.2)]' : 'border-[#dfe8f2] bg-white shadow-[0_16px_45px_rgba(32,66,103,.06)]'}`}><span className={`text-sm font-bold ${index === 1 ? 'text-white/65' : 'text-[#0866ff]'}`}>{number}</span><h3 className="mt-12 text-xl font-bold">{title}</h3><p className={`mt-3 text-sm leading-6 ${index === 1 ? 'text-white/70' : 'text-[#66768b]'}`}>{body}</p></motion.article>)}</div></Section>

    <Section eyebrow="Deux façons de participer" title="Demandez de l’aide. Ou partagez votre savoir-faire." intro="Deux parcours réunis dans une même communauté." className="bg-[#f7faff]"><div className="grid gap-5 lg:grid-cols-2"><motion.article {...reveal} className="relative overflow-hidden rounded-[2rem] border border-[#dce7f3] bg-white p-8 shadow-[0_22px_60px_rgba(32,66,103,.08)] sm:p-10"><UsersRound className="h-8 w-8 text-[#0866ff]" /><p className="mt-8 text-xs font-bold uppercase tracking-[.2em] text-[#0866ff]">Je cherche de l’aide</p><h3 className="mt-3 text-3xl font-bold tracking-[-.035em]">Retrouvez du temps pour ce qui compte.</h3><p className="mt-4 leading-7 text-[#64748b]">Présentez votre besoin une fois et découvrez des personnes locales intéressées.</p><a href="#clients" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#0866ff]">Expérience client <ArrowRight className="h-4 w-4" /></a></motion.article><motion.article {...reveal} className="relative overflow-hidden rounded-[2rem] bg-[#0b1930] p-8 text-white shadow-[0_28px_70px_rgba(11,25,48,.2)] sm:p-10"><BadgeCheck className="h-8 w-8 text-[#7eb3ff]" /><p className="mt-8 text-xs font-bold uppercase tracking-[.2em] text-[#7eb3ff]">Je veux aider</p><h3 className="mt-3 text-3xl font-bold tracking-[-.035em]">Faites rayonner ce que vous savez faire.</h3><p className="mt-4 leading-7 text-white/65">Trouvez des occasions locales et bâtissez un profil qui valorise votre contribution.</p><a href="#helpers" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-white">Parcours helper <ArrowRight className="h-4 w-4" /></a></motion.article></div></Section>

    <Section id="clients" eyebrow="Pour les clients" title="Moins de recherche. Plus de confiance." intro="Une expérience claire du besoin jusqu’au choix."><div className="grid gap-5 lg:grid-cols-12"><motion.div {...reveal} className="rounded-[2rem] bg-[linear-gradient(145deg,#0866ff,#0648aa)] p-8 text-white shadow-[0_28px_70px_rgba(8,102,255,.2)] sm:p-12 lg:col-span-7"><p className="text-sm font-semibold text-white/65">Une demande, plusieurs possibilités</p><h3 className="mt-4 max-w-xl text-3xl font-bold sm:text-4xl">L’aide locale, sans le bouche-à-oreille compliqué.</h3><div className="mt-9 grid gap-3 sm:grid-cols-3">{['Profils lisibles', 'Avis utiles', 'Expérience mobile'].map((item) => <p key={item} className="flex items-center gap-2 rounded-2xl bg-white/10 px-4 py-3 text-sm font-semibold"><Check className="h-4 w-4" />{item}</p>)}</div></motion.div><motion.div {...reveal} className="overflow-hidden rounded-[2rem] border border-[#dce7f3] bg-[#eff6ff] lg:col-span-5"><img src="/brand/client-home-hero-trust.webp" alt="Aperçu de l’expérience client Link Help" className="h-full min-h-72 w-full object-cover" loading="lazy" /></motion.div></div></Section>

    <Section id="helpers" eyebrow="Pour les helpers" title="Votre savoir-faire mérite d’être reconnu." intro="Une présence locale qui progresse avec chaque expérience." className="bg-[#f7faff]"><div className="grid gap-5 lg:grid-cols-12"><motion.div {...reveal} className="relative overflow-hidden rounded-[2rem] border border-[#dce7f3] bg-[radial-gradient(circle_at_30%_20%,#fff,#eaf3ff_70%)] p-8 lg:col-span-5"><span className="absolute left-7 top-7 rounded-full bg-white/80 px-3 py-2 text-xs font-bold text-[#0866ff] shadow-sm">Max Québec</span><img src="/assets/characters/max-quebec/arms-crossed.png" alt="Max Québec présentant le parcours helper" className="mx-auto h-80 object-contain" loading="lazy" /></motion.div><motion.div {...reveal} className="rounded-[2rem] border border-[#dce7f3] bg-white p-8 shadow-[0_20px_55px_rgba(32,66,103,.07)] sm:p-10 lg:col-span-7"><h3 className="text-3xl font-bold">Progressez avec chaque expérience.</h3><p className="mt-4 max-w-xl leading-7 text-[#64748b]">Profils, évaluations, badges et progression rendent votre contribution visible.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{['Opportunités locales', 'Réputation par les avis', 'Badges de progression', 'Forces mises en valeur'].map((item) => <div key={item} className="flex items-center gap-3 rounded-2xl border border-[#e2eaf3] bg-[#fbfdff] p-4 text-sm font-semibold"><BadgeCheck className="h-5 w-5 text-[#0866ff]" />{item}</div>)}</div></motion.div></div></Section>

    <Section eyebrow="Services du quotidien" title="De petits coups de main. Un grand impact local." intro="Des besoins pratiques et non réglementés, près de chez vous."><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{landingServices.map(({ label, icon: Icon }, index) => <motion.div key={label} {...reveal} whileHover={reduceMotion ? undefined : { y: -4 }} className={`rounded-[1.4rem] border p-5 ${index < 4 ? 'border-[#d7e5f5] bg-[#f7fbff]' : 'border-[#e3eaf2] bg-white'}`}><span className="flex h-10 w-10 items-center justify-center rounded-xl bg-white text-[#0866ff] shadow-sm"><Icon className="h-5 w-5" /></span><p className="mt-6 text-sm font-bold">{label}</p></motion.div>)}</div></Section>

    <Section eyebrow="LinkCredits" title="Une façon simple d’accéder aux opportunités." intro="Les LinkCredits font partie du parcours helper et rendent l’accès aux candidatures plus lisible." className="bg-[#09172d]" dark><div className="grid gap-5 lg:grid-cols-12"><motion.div {...reveal} className="relative overflow-hidden rounded-[2rem] border border-white/10 bg-white/[.06] p-8 text-white backdrop-blur sm:p-10 lg:col-span-7"><WalletCards className="h-8 w-8 text-[#7eb3ff]" /><h3 className="mt-8 max-w-lg text-3xl font-bold">Des crédits conçus pour une expérience transparente.</h3><p className="mt-4 max-w-xl leading-7 text-white/65">Les helpers utilisent des LinkCredits pour accéder aux occasions pertinentes. Les détails seront présentés clairement au lancement.</p></motion.div><motion.div {...reveal} className="relative flex min-h-80 items-center justify-center overflow-hidden rounded-[2rem] border border-white/10 bg-[radial-gradient(circle,rgba(8,102,255,.32),rgba(255,255,255,.04)_65%)] p-8 lg:col-span-5"><img src="/brand/linkcredit-coin-icon.webp" alt="Icône officielle LinkCredit" className="w-44 drop-shadow-[0_25px_30px_rgba(0,0,0,.3)]" loading="lazy" /></motion.div></div></Section>

    <Section eyebrow="Pourquoi Link Help" title="La confiance se construit dans les détails." className="bg-[#f7faff]"><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{[[Clock3, 'Simple dès le départ', 'Un parcours court et compréhensible.'], [MapPin, 'Vraiment local', 'Des connexions dans votre communauté.'], [Star, 'Des avis utiles', 'La réputation aide à choisir.'], [BadgeCheck, 'Des profils clairs', 'L’essentiel présenté simplement.'], [ShieldCheck, 'Pensé avec prudence', 'Une expérience saine et lisible.'], [Check, 'Moins de friction', 'Une interface mobile accessible.']].map(([Icon, title, body], index) => <motion.article key={String(title)} {...reveal} className={`rounded-[1.6rem] border p-6 ${index === 0 ? 'border-[#0866ff] bg-[#0866ff] text-white shadow-[0_20px_50px_rgba(8,102,255,.18)]' : 'border-[#e0e8f1] bg-white'}`}><Icon className={`h-6 w-6 ${index === 0 ? 'text-white' : 'text-[#0866ff]'}`} /><h3 className="mt-7 text-lg font-bold">{String(title)}</h3><p className={`mt-2 text-sm leading-6 ${index === 0 ? 'text-white/70' : 'text-[#66768b]'}`}>{String(body)}</p></motion.article>)}</div></Section>

    <Section eyebrow="Progression helper" title="Chaque étape raconte votre parcours."><div className="relative grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-6"><div className="absolute left-[8%] right-[8%] top-7 hidden h-px bg-[#d7e3f0] md:block" />{helperBadges.map((badge, index) => <motion.div key={badge} {...reveal} className="relative text-center"><div className={`mx-auto flex h-14 w-14 items-center justify-center rounded-full border text-sm font-bold shadow-sm ${index === helperBadges.length - 1 ? 'border-[#0866ff] bg-[#0866ff] text-white' : 'border-[#d9e5f2] bg-white text-[#0866ff]'}`}>{index + 1}</div><p className="mt-4 text-sm font-bold">{badge}</p></motion.div>)}</div></Section>

    <Section id="faq" eyebrow="FAQ" title="Les réponses avant de vous inscrire." className="bg-[#f7faff]"><div className="mx-auto max-w-4xl space-y-3">{faqs.map((faq) => <details key={faq.question} className="group rounded-2xl border border-[#dfe7f0] bg-white px-5 py-1 shadow-sm sm:px-6"><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-5 text-left font-bold focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#0866ff]/15">{faq.question}<span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-[#eef6ff]"><ChevronDown className="h-4 w-4 text-[#0866ff] transition group-open:rotate-180" /></span></summary><p className="max-w-2xl pb-5 text-sm leading-7 text-[#66768b]">{faq.answer}</p></details>)}</div></Section>

    <section className="px-5 py-20 sm:px-8 sm:py-28"><motion.div {...reveal} className="mx-auto grid max-w-6xl items-center gap-10 overflow-hidden rounded-[2.5rem] bg-[linear-gradient(135deg,#0b1930,#0b326e)] p-7 text-white shadow-[0_35px_90px_rgba(11,25,48,.22)] sm:p-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#7eb3ff]">Prêt pour le lancement</p><h2 className="mt-4 text-balance text-3xl font-bold tracking-[-.045em] sm:text-5xl">Soyez là dès le premier coup de main.</h2><p className="mt-5 leading-7 text-white/65">Recevez un accès anticipé et les nouvelles importantes.</p><p className="mt-6 flex items-center gap-2 text-sm font-semibold"><Coins className="h-5 w-5 text-[#7eb3ff]" /> Gratuit et sans engagement.</p></div><WaitlistForm compact /></motion.div></section>
  </main><footer className="border-t border-[#e1e9f2] bg-white px-5 py-10 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-8 sm:flex-row sm:items-end sm:justify-between"><div><Logo className="h-9 w-auto" /><div className="mt-3"><ByFluxBadge className="text-[#7b8ba1]" /></div><p className="mt-4 text-sm text-[#6b7a8e]">L’aide locale, rendue plus simple.</p></div><div className="flex flex-wrap gap-6 text-sm font-semibold text-[#536277]"><a href="#fonctionnement">Fonctionnement</a><a href="#clients">Clients</a><a href="#helpers">Helpers</a><a href="#faq">FAQ</a><a href="/contato">Contact</a></div></div><div className="mx-auto mt-8 max-w-7xl border-t border-[#edf1f5] pt-6 text-xs text-[#8a98aa]">© {new Date().getFullYear()} Link Help. Tous droits réservés.</div></footer></div></MotionConfig>;
}
