import { useEffect, useState, type ReactNode } from 'react';
import { motion, useReducedMotion } from 'motion/react';
import { ArrowRight, BadgeCheck, Check, ChevronDown, Clock3, Menu, ShieldCheck, Star, UsersRound, X } from 'lucide-react';
import { Logo } from '@/components/ui/Logo';
import { ByFluxBadge } from '@/components/brand/ByFluxBadge';
import { WaitlistForm } from './WaitlistForm';
import { faqs, helperBadges, landingServices } from './landingData';

const ease = [0.22, 1, 0.36, 1] as const;
const reveal = { initial: { opacity: 0, y: 28 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: '-70px' }, transition: { duration: .65, ease } };

function LandingSeo() {
  useEffect(() => {
    const title = 'Link Help Québec | La liste d’attente est ouverte';
    const description = 'Trouvez un coup de main local ou offrez vos services au Québec. Rejoignez gratuitement la liste d’attente de Link Help.';
    document.title = title;
    document.documentElement.lang = 'fr-CA';
    const entries: [string, string, string][] = [
      ['name', 'description', description], ['property', 'og:title', title], ['property', 'og:description', description],
      ['property', 'og:type', 'website'], ['property', 'og:url', 'https://www.linkhelp.app/'],
      ['property', 'og:image', 'https://www.linkhelp.app/brand/linkhelp-app-source.png'], ['name', 'twitter:card', 'summary_large_image'],
      ['name', 'twitter:title', title], ['name', 'twitter:description', description],
    ];
    const created: HTMLElement[] = [];
    for (const [attribute, key, value] of entries) {
      let node = document.head.querySelector(`meta[${attribute}="${key}"]`) as HTMLMetaElement | null;
      if (!node) { node = document.createElement('meta'); node.setAttribute(attribute, key); document.head.appendChild(node); created.push(node); }
      node.content = value;
    }
    const canonical = document.head.querySelector('link[rel="canonical"]') as HTMLLinkElement | null ?? document.head.appendChild(document.createElement('link'));
    canonical.rel = 'canonical'; canonical.href = 'https://www.linkhelp.app/';
    const json = document.createElement('script'); json.type = 'application/ld+json'; json.textContent = JSON.stringify({ '@context': 'https://schema.org', '@type': 'WebSite', name: 'Link Help', url: 'https://www.linkhelp.app/', inLanguage: 'fr-CA', description }); document.head.appendChild(json);
    return () => { created.forEach((node) => node.remove()); json.remove(); };
  }, []);
  return null;
}

function Section({ id, eyebrow, title, intro, children, className = '' }: { id?: string; eyebrow?: string; title: string; intro?: string; children: ReactNode; className?: string }) {
  return <section id={id} className={`scroll-mt-24 px-5 py-20 sm:px-8 sm:py-28 ${className}`}><div className="mx-auto max-w-7xl"><motion.div {...reveal} className="mx-auto mb-12 max-w-3xl text-center">{eyebrow && <p className="text-xs font-bold uppercase tracking-[.2em] text-[#0866ff]">{eyebrow}</p>}<h2 className="mt-3 text-balance text-3xl font-bold leading-tight tracking-[-.035em] text-[#0b1930] sm:text-5xl">{title}</h2>{intro && <p className="mx-auto mt-5 max-w-2xl text-base leading-7 text-[#5e6d82] sm:text-lg">{intro}</p>}</motion.div>{children}</div></section>;
}

function LandingNavbar() {
  const [open, setOpen] = useState(false);
  const links = [['#fonctionnement', 'Comment ça fonctionne'], ['#clients', 'Pour les clients'], ['#helpers', 'Pour les helpers'], ['#faq', 'FAQ']] as const;
  return <header className="sticky top-0 z-50 border-b border-[#dce7f3]/80 bg-white/90 backdrop-blur-xl"><nav aria-label="Navigation principale" className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 sm:px-8"><a href="#accueil" aria-label="Link Help — accueil"><Logo className="h-9 w-auto" /></a><div className="hidden items-center gap-7 lg:flex">{links.map(([href,label]) => <a key={href} href={href} className="text-sm font-semibold text-[#536277] transition hover:text-[#0866ff]">{label}</a>)}</div><a href="#liste" className="hidden min-h-11 items-center rounded-xl bg-[#0866ff] px-5 text-sm font-bold text-white shadow-[0_10px_24px_rgba(8,102,255,.2)] transition hover:-translate-y-0.5 lg:inline-flex">Rejoindre la liste d’attente</a><button type="button" onClick={() => setOpen(!open)} aria-expanded={open} aria-label={open ? 'Fermer le menu' : 'Ouvrir le menu'} className="flex h-11 w-11 items-center justify-center rounded-xl border border-[#dce7f3] text-[#0b1930] lg:hidden">{open ? <X /> : <Menu />}</button></nav>{open && <motion.div initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: 'auto' }} className="border-t border-[#e6edf5] bg-white px-5 pb-5 lg:hidden">{links.map(([href,label]) => <a key={href} href={href} onClick={() => setOpen(false)} className="block border-b border-[#edf2f7] py-4 text-sm font-semibold text-[#314159]">{label}</a>)}<a href="#liste" onClick={() => setOpen(false)} className="mt-5 flex min-h-12 items-center justify-center rounded-xl bg-[#0866ff] text-sm font-bold text-white">Rejoindre la liste</a></motion.div>}</header>;
}

function ProductPreview() {
  return <div className="relative mx-auto max-w-xl"><div className="absolute -inset-12 rounded-full bg-[#dcecff] blur-3xl" /><motion.div animate={{ y: [0, -7, 0] }} transition={{ duration: 6, repeat: Infinity, ease: 'easeInOut' }} className="relative rounded-[2.25rem] border border-white bg-white p-3 shadow-[0_40px_100px_rgba(29,74,126,.18)]"><div className="overflow-hidden rounded-[1.75rem] bg-[#f2f7fd] p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold text-[#728198]">Bonjour, Camille</p><p className="text-lg font-bold text-[#0b1930]">De quoi avez-vous besoin?</p></div><img src="/assets/characters/max-quebec/thumbs-up-bust.png" alt="Max Québec, mascotte de Link Help" className="h-20 w-20 object-contain" loading="eager" /></div><div className="mt-4 rounded-2xl bg-[#0866ff] p-5 text-white"><p className="text-xs font-semibold text-white/70">Près de chez vous</p><p className="mt-1 text-xl font-bold">Des helpers locaux, quand ça compte.</p><div className="mt-5 flex gap-2"><span className="rounded-lg bg-white/15 px-3 py-2 text-xs">Ménage</span><span className="rounded-lg bg-white/15 px-3 py-2 text-xs">Assemblage</span></div></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white p-4"><UsersRound className="h-5 w-5 text-[#0866ff]" /><p className="mt-7 text-sm font-bold text-[#0b1930]">Helpers locaux</p><p className="mt-1 text-xs text-[#728198]">Profils et avis</p></div><div className="rounded-2xl bg-white p-4"><Clock3 className="h-5 w-5 text-[#0866ff]" /><p className="mt-7 text-sm font-bold text-[#0b1930]">Simple et rapide</p><p className="mt-1 text-xs text-[#728198]">En quelques étapes</p></div></div></div></motion.div><div className="absolute -bottom-6 -left-5 rounded-2xl border border-[#dce7f3] bg-white p-4 shadow-xl"><div className="flex -space-x-2">{['thumbs-up','arms-crossed','holding-phone'].map((name) => <img key={name} src={`/assets/characters/max-quebec/${name}.png`} alt="" className="h-9 w-9 rounded-full border-2 border-white bg-[#eaf3ff] object-cover" />)}</div><p className="mt-2 text-xs font-semibold text-[#40516a]">Une communauté qui se prépare</p></div></div>;
}

export function LandingPagePremium() {
  const reduceMotion = useReducedMotion();
  const scrollToForm = () => document.querySelector('#liste input')?.scrollIntoView({ behavior: reduceMotion ? 'auto' : 'smooth', block: 'center' });
  return <div className="min-h-screen bg-white font-sans text-[#0b1930]"><LandingSeo /><LandingNavbar />
    <main>
      <section id="accueil" className="relative overflow-hidden px-5 pb-20 pt-14 sm:px-8 sm:pb-28 sm:pt-20"><div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_20%,#e7f1ff_0,transparent_38%),linear-gradient(180deg,#fbfdff_0%,#fff_100%)]" /><div className="relative mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[1.05fr_.95fr]"><motion.div initial={{ opacity: 0, y: 25 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .7, ease }}><span className="inline-flex items-center gap-2 rounded-full border border-[#cfe0f4] bg-white px-3 py-2 text-xs font-bold text-[#0866ff] shadow-sm"><span className="h-2 w-2 rounded-full bg-[#0866ff]" /> Bientôt au Québec</span><h1 className="mt-7 max-w-3xl text-balance text-[2.8rem] font-bold leading-[1.02] tracking-[-.055em] text-[#0b1930] sm:text-6xl lg:text-7xl">Un coup de main local. <span className="text-[#0866ff]">Au bon moment.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-[#5b6b80] sm:text-xl">Link Help connecte les personnes qui ont besoin d’aide avec des helpers de leur communauté — simplement et humainement.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button onClick={scrollToForm} className="inline-flex min-h-13 items-center justify-center gap-2 rounded-xl bg-[#0866ff] px-6 text-sm font-bold text-white shadow-[0_16px_35px_rgba(8,102,255,.24)] transition hover:-translate-y-0.5">Rejoindre la liste <ArrowRight className="h-4 w-4" /></button><a href="#fonctionnement" className="inline-flex min-h-13 items-center justify-center rounded-xl border border-[#d4e0ed] bg-white px-6 text-sm font-bold text-[#25364d] transition hover:border-[#0866ff]/40">Découvrir Link Help</a></div><div className="mt-7 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-[#65758a]"><span className="inline-flex items-center gap-2"><Check className="h-4 w-4 text-[#0866ff]" /> Gratuit</span><span className="inline-flex items-center gap-2"><Check className="h-4 w-4 text-[#0866ff]" /> Aucun engagement</span><span className="inline-flex items-center gap-2"><Check className="h-4 w-4 text-[#0866ff]" /> Accès prioritaire</span></div></motion.div><motion.div initial={{ opacity: 0, x: 30 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: .8, delay: .1, ease }}><ProductPreview /></motion.div></div></section>

      <section id="liste" className="scroll-mt-24 border-y border-[#e5edf6] bg-[#f7faff] px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.85fr_1.15fr]"><motion.div {...reveal}><p className="text-xs font-bold uppercase tracking-[.2em] text-[#0866ff]">Soyez parmi les premiers</p><h2 className="mt-3 text-3xl font-bold tracking-[-.035em] sm:text-5xl">Votre communauté nous aide à choisir où lancer.</h2><p className="mt-5 max-w-lg text-lg leading-8 text-[#5e6d82]">Dites-nous où vous êtes et comment Link Help pourrait vous être utile. Votre inscription façonne directement le prélancement.</p></motion.div><motion.div {...reveal}><WaitlistForm /></motion.div></div></section>

      <Section id="fonctionnement" eyebrow="Comment ça fonctionne" title="Demander de l’aide devrait rester simple." intro="Trois étapes claires, sans parcours compliqué."><div className="grid gap-5 md:grid-cols-3">{[['01','Publiez votre demande','Décrivez votre besoin, votre secteur et le moment qui vous convient.'],['02','Recevez des candidatures','Découvrez des helpers intéressés, leur profil et leur réputation.'],['03','Choisissez votre helper','Échangez, comparez et choisissez la personne qui vous convient.']].map(([number,title,body]) => <motion.article key={number} {...reveal} className="rounded-[1.75rem] border border-[#dde7f2] bg-white p-7 shadow-[0_18px_50px_rgba(32,66,103,.07)]"><span className="text-sm font-bold text-[#0866ff]">{number}</span><h3 className="mt-10 text-xl font-bold">{title}</h3><p className="mt-3 text-sm leading-6 text-[#66768b]">{body}</p></motion.article>)}</div></Section>

      <Section id="clients" eyebrow="Pour les clients" title="Plus de temps pour ce qui compte vraiment." intro="Trouvez une personne locale pour les tâches du quotidien, avec une expérience claire du début à la fin." className="bg-[#f7faff]"><div className="grid items-center gap-12 lg:grid-cols-2"><motion.div {...reveal} className="rounded-[2rem] bg-[#0866ff] p-8 text-white sm:p-12"><p className="text-sm font-semibold text-white/70">Une demande, plusieurs possibilités</p><h3 className="mt-3 text-3xl font-bold">L’aide locale, sans les recherches interminables.</h3><div className="mt-8 space-y-4">{['Des profils faciles à comprendre','Des avis pour mieux choisir','Une expérience pensée pour le mobile'].map((item) => <p key={item} className="flex items-center gap-3 text-sm font-semibold"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-white/15"><Check className="h-4 w-4" /></span>{item}</p>)}</div></motion.div><motion.div {...reveal}><img src="/brand/client-home-hero-trust.webp" alt="Aperçu de l’expérience client Link Help" className="mx-auto w-full max-w-lg rounded-[2rem] object-cover shadow-[0_25px_70px_rgba(33,70,112,.15)]" loading="lazy" /></motion.div></div></Section>

      <Section id="helpers" eyebrow="Pour les helpers" title="Votre savoir-faire mérite d’être reconnu." intro="Créez votre réputation au fil des services et faites grandir votre présence locale."><div className="grid items-center gap-12 lg:grid-cols-[.9fr_1.1fr]"><motion.div {...reveal} className="relative rounded-[2rem] bg-[#edf5ff] p-8"><img src="/assets/characters/max-quebec/arms-crossed.png" alt="Max Québec présentant le parcours helper" className="mx-auto h-80 object-contain" loading="lazy" /></motion.div><motion.div {...reveal}><h3 className="text-3xl font-bold">Progressez avec chaque expérience.</h3><p className="mt-4 text-base leading-7 text-[#64748b]">Profils, évaluations, badges et progression rendent votre contribution visible — sans transformer l’expérience en compétition excessive.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{['Opportunités près de chez vous','Réputation construite par les avis','Badges de progression','Profil qui met vos forces en valeur'].map((item) => <div key={item} className="flex items-center gap-3 rounded-xl border border-[#dde7f2] p-4 text-sm font-semibold"><BadgeCheck className="h-5 w-5 text-[#0866ff]" />{item}</div>)}</div></motion.div></div></Section>

      <Section eyebrow="Services du quotidien" title="Un monde de petits coups de main." intro="Une sélection pensée pour les besoins pratiques, non réglementés, près de chez vous." className="bg-[#f7faff]"><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-4">{landingServices.map(({ label, icon: Icon }) => <motion.div key={label} {...reveal} whileHover={{ y: -4 }} className="rounded-2xl border border-[#dfe8f2] bg-white p-5 shadow-sm"><Icon className="h-6 w-6 text-[#0866ff]" /><p className="mt-7 text-sm font-bold text-[#26364d]">{label}</p></motion.div>)}</div></Section>

      <Section eyebrow="Pourquoi Link Help" title="La confiance se construit dans les détails."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{[[Clock3,'Simple dès le départ','Un parcours court et compréhensible.'],[UsersRound,'Vraiment local','Des connexions dans votre communauté.'],[Star,'Des avis utiles','La réputation vous aide à choisir.'],[BadgeCheck,'Des profils clairs','L’essentiel, présenté simplement.'],[ShieldCheck,'Pensé avec prudence','Des règles qui favorisent une expérience saine.'],[Check,'Moins de friction','Une interface mobile rapide et accessible.']].map(([Icon,title,body]) => <motion.article key={String(title)} {...reveal} className="rounded-2xl border border-[#e0e8f1] p-6"><Icon className="h-6 w-6 text-[#0866ff]" /><h3 className="mt-6 text-lg font-bold">{String(title)}</h3><p className="mt-2 text-sm leading-6 text-[#66768b]">{String(body)}</p></motion.article>)}</div></Section>

      <Section eyebrow="Progression helper" title="Chaque étape raconte votre parcours." className="bg-[#0b1930]"><div className="relative grid gap-4 md:grid-cols-6"><div className="absolute left-[8%] right-[8%] top-7 hidden h-px bg-white/15 md:block" />{helperBadges.map((badge,index) => <motion.div key={badge} {...reveal} className="relative text-center"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full border border-white/15 bg-[#132944] text-sm font-bold text-white shadow-lg">{index + 1}</div><p className="mt-4 text-sm font-bold text-white">{badge}</p></motion.div>)}</div></Section>

      <Section id="faq" eyebrow="FAQ" title="Avant de vous inscrire."><div className="mx-auto max-w-3xl divide-y divide-[#dfe7f0] border-y border-[#dfe7f0]">{faqs.map((faq) => <details key={faq.question} className="group py-5"><summary className="flex cursor-pointer list-none items-center justify-between gap-5 text-left font-bold text-[#1d2d44] focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#0866ff]/15">{faq.question}<ChevronDown className="h-5 w-5 shrink-0 text-[#0866ff] transition group-open:rotate-180" /></summary><motion.p initial={{ opacity: 0 }} whileInView={{ opacity: 1 }} className="max-w-2xl pt-3 text-sm leading-7 text-[#66768b]">{faq.answer}</motion.p></details>)}</div></Section>

      <section className="px-5 py-20 sm:px-8 sm:py-28"><motion.div {...reveal} className="mx-auto grid max-w-6xl items-center gap-10 overflow-hidden rounded-[2.5rem] bg-[#edf5ff] p-7 sm:p-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-[#0866ff]">Prêt pour le lancement</p><h2 className="mt-3 text-3xl font-bold tracking-[-.035em] sm:text-5xl">Soyez là dès le premier coup de main.</h2><p className="mt-5 text-base leading-7 text-[#5e6d82]">Recevez un accès anticipé, les nouvelles importantes et des invitations aux premiers tests.</p></div><WaitlistForm compact /></motion.div></section>
    </main>
    <footer className="border-t border-[#e1e9f2] bg-white px-5 py-10 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-8 sm:flex-row sm:items-end sm:justify-between"><div><Logo className="h-9 w-auto" /><div className="mt-3"><ByFluxBadge className="text-[#7b8ba1]" /></div><p className="mt-4 max-w-sm text-sm text-[#6b7a8e]">L’aide locale, rendue plus simple.</p></div><div className="flex flex-wrap gap-x-6 gap-y-3 text-sm font-semibold text-[#536277]"><a href="#fonctionnement">Fonctionnement</a><a href="#clients">Clients</a><a href="#helpers">Helpers</a><a href="#faq">FAQ</a><a href="/contato">Confidentialité</a></div></div><div className="mx-auto mt-8 max-w-7xl border-t border-[#edf1f5] pt-6 text-xs text-[#8a98aa]">© {new Date().getFullYear()} Link Help. Tous droits réservés.</div></footer>
  </div>;
}
