import { useState } from 'react';
import { MotionConfig, motion } from 'motion/react';
import { ArrowRight, BadgeCheck, Check, ChevronDown, Menu, ShieldCheck, Star, X } from 'lucide-react';
import { Logo } from '@/components/ui/Logo';
import { ByFluxBadge } from '@/components/brand/ByFluxBadge';
import { LandingHeroShowcase } from './LandingHeroShowcase';
import { WaitlistForm } from './WaitlistForm';
import { faqs, helperBadges, landingServices } from './landingData';

const reveal = { initial: { opacity: 0, y: 22 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true, margin: '-60px' }, transition: { duration: 0.6 } };

function Navbar() {
  const [open, setOpen] = useState(false);
  const links = [['#fonctionnement', 'Comment ça fonctionne'], ['#services', 'Services'], ['#confiance', 'Confiance'], ['#faq', 'FAQ']] as const;
  return <header className="sticky top-0 z-50 border-b border-[#e3eaf3] bg-white/92 backdrop-blur-2xl"><nav aria-label="Navigation principale" className="mx-auto flex h-[4.5rem] max-w-[90rem] items-center justify-between px-5 sm:px-8"><a href="#accueil" aria-label="Link Help — accueil" className="rounded-lg focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#0866ff]/20"><Logo className="h-10 w-auto" /></a><div className="hidden items-center gap-8 lg:flex">{links.map(([href, label]) => <a key={href} href={href} className="text-sm font-semibold text-[#25364d] transition hover:text-[#0866ff]">{label}</a>)}</div><a href="#liste" className="hidden min-h-11 items-center gap-2 rounded-xl bg-[#0866ff] px-5 text-sm font-bold text-white shadow-[0_12px_26px_rgba(8,102,255,.22)] lg:inline-flex">Rejoindre la liste <ArrowRight className="h-4 w-4" /></a><button type="button" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="reference-mobile-menu" aria-label={open ? 'Fermer le menu' : 'Ouvrir le menu'} className="flex h-11 w-11 items-center justify-center rounded-xl border border-[#dce7f3] lg:hidden">{open ? <X /> : <Menu />}</button></nav>{open && <div id="reference-mobile-menu" className="border-t border-[#e6edf5] bg-white px-5 pb-5 lg:hidden">{links.map(([href, label]) => <a key={href} href={href} onClick={() => setOpen(false)} className="block border-b border-[#edf2f7] py-4 text-sm font-semibold">{label}</a>)}<a href="#liste" onClick={() => setOpen(false)} className="mt-5 flex min-h-12 items-center justify-center rounded-xl bg-[#0866ff] text-sm font-bold text-white">Rejoindre la liste</a></div>}</header>;
}

function Section({ id, eyebrow, title, children, tinted = false }: { id?: string; eyebrow: string; title: string; children: React.ReactNode; tinted?: boolean }) {
  return <section id={id} className={`scroll-mt-24 px-5 py-20 sm:px-8 sm:py-24 ${tinted ? 'bg-[#f7faff]' : 'bg-white'}`}><div className="mx-auto max-w-7xl"><motion.div {...reveal} className="mx-auto mb-12 max-w-3xl text-center"><p className="text-xs font-bold uppercase tracking-[.22em] text-[#0866ff]">{eyebrow}</p><h2 className="mt-3 text-balance text-3xl font-bold tracking-[-.045em] text-[#0b1930] sm:text-5xl">{title}</h2></motion.div>{children}</div></section>;
}

export function LandingPageReference() {
  return <MotionConfig reducedMotion="user"><div className="min-h-screen overflow-x-hidden bg-white font-sans text-[#0b1930]"><Navbar /><main><LandingHeroShowcase />
    <Section id="fonctionnement" eyebrow="Comment ça fonctionne" title="Simple du début à la fin."><div className="grid gap-4 md:grid-cols-3">{[['01', 'Publiez votre demande', 'Décrivez clairement le coup de main dont vous avez besoin.'], ['02', 'Découvrez les helpers', 'Consultez les profils et les informations disponibles.'], ['03', 'Choisissez votre helper', 'Échangez et retenez la personne qui vous convient.']].map(([number, title, body], index) => <motion.article key={number} {...reveal} className={`rounded-[1.75rem] border p-7 text-left ${index === 1 ? 'border-[#0866ff] bg-[#0866ff] text-white shadow-[0_22px_55px_rgba(8,102,255,.2)]' : 'border-[#dfe7f1] bg-white shadow-[0_14px_38px_rgba(32,66,103,.06)]'}`}><span className={`flex h-10 w-10 items-center justify-center rounded-full text-sm font-bold ${index === 1 ? 'bg-white/15' : 'bg-[#eaf3ff] text-[#0866ff]'}`}>{number}</span><h3 className="mt-8 text-xl font-bold">{title}</h3><p className={`mt-3 text-sm leading-6 ${index === 1 ? 'text-white/70' : 'text-[#65758a]'}`}>{body}</p></motion.article>)}</div></Section>

    <Section id="services" eyebrow="Services du quotidien" title="Des services pour vous simplifier la vie." tinted><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{landingServices.map(({ label, icon: Icon }) => <motion.div key={label} {...reveal} className="rounded-2xl border border-[#dfe7f1] bg-white p-4 text-center shadow-[0_10px_28px_rgba(32,66,103,.05)]"><span className="mx-auto flex h-10 w-10 items-center justify-center rounded-xl bg-[#eaf3ff] text-[#0866ff]"><Icon className="h-5 w-5" /></span><p className="mt-4 text-xs font-bold leading-5">{label}</p></motion.div>)}</div><p className="mt-5 text-center text-xs text-[#7b8ba1]">Les métiers réglementés ne font pas partie de l’offre Link Help.</p></Section>

    <Section id="confiance" eyebrow="Pourquoi Link Help" title="La confiance se construit dans les détails."><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[[ShieldCheck, 'Pensé avec prudence', 'Une expérience claire et encadrée.'], [Star, 'Réputation visible', 'Des informations utiles pour mieux choisir.'], [BadgeCheck, 'Profils lisibles', 'L’essentiel présenté simplement.'], [Check, 'Expérience mobile', 'Pensée pour vous accompagner partout.']].map(([Icon, title, body], index) => <motion.article key={String(title)} {...reveal} className={`rounded-[1.5rem] border p-6 ${index === 0 ? 'border-[#0866ff] bg-[#0866ff] text-white shadow-[0_20px_45px_rgba(8,102,255,.18)]' : 'border-[#dfe7f1] bg-white'}`}><Icon className={`h-6 w-6 ${index === 0 ? 'text-white' : 'text-[#0866ff]'}`} /><h3 className="mt-7 font-bold">{String(title)}</h3><p className={`mt-2 text-sm leading-6 ${index === 0 ? 'text-white/70' : 'text-[#65758a]'}`}>{String(body)}</p></motion.article>)}</div></Section>

    <section className="bg-[#071f58] px-5 py-16 text-white sm:px-8"><div className="mx-auto grid max-w-7xl items-center gap-8 lg:grid-cols-[.8fr_1.2fr]"><motion.div {...reveal}><p className="text-xs font-bold uppercase tracking-[.22em] text-[#7eb3ff]">LinkCredits et progression</p><h2 className="mt-3 text-3xl font-bold tracking-[-.04em] sm:text-4xl">Votre réputation évolue avec vous.</h2><p className="mt-4 max-w-lg leading-7 text-white/65">Les LinkCredits et les badges accompagnent le parcours helper avec une progression visible.</p></motion.div><div className="grid grid-cols-3 gap-3 sm:grid-cols-6">{helperBadges.map((badge, index) => <motion.div key={badge} {...reveal} className="text-center"><span className={`mx-auto flex h-12 w-12 items-center justify-center rounded-full border text-sm font-bold ${index === 5 ? 'border-[#7eb3ff] bg-[#0866ff]' : 'border-white/15 bg-white/10'}`}>{index + 1}</span><p className="mt-3 text-[11px] font-semibold text-white/75">{badge}</p></motion.div>)}</div></div></section>

    <Section id="faq" eyebrow="Questions fréquentes" title="Avant de rejoindre la liste." tinted><div className="mx-auto grid max-w-5xl gap-3 md:grid-cols-2">{faqs.map((faq) => <details key={faq.question} className="group rounded-2xl border border-[#dfe7f1] bg-white px-5 py-1"><summary className="flex min-h-16 cursor-pointer list-none items-center justify-between gap-4 text-sm font-bold focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-[#0866ff]/15">{faq.question}<ChevronDown className="h-4 w-4 shrink-0 text-[#0866ff] transition group-open:rotate-180" /></summary><p className="pb-5 text-sm leading-6 text-[#65758a]">{faq.answer}</p></details>)}</div></Section>

    <section className="px-5 py-16 sm:px-8 sm:py-20"><div className="mx-auto grid max-w-6xl items-center gap-8 rounded-[2.25rem] bg-[linear-gradient(135deg,#eaf3ff,#f8fbff)] p-7 sm:p-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#0866ff]">Ne manquez rien du lancement</p><h2 className="mt-3 text-3xl font-bold tracking-[-.04em]">Soyez parmi les premiers.</h2><p className="mt-4 text-[#65758a]">Recevez les nouvelles importantes pour votre région.</p></div><WaitlistForm compact /></div></section>
  </main><footer className="border-t border-[#dfe7f1] bg-[#061b4a] px-5 py-10 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-8 sm:flex-row sm:items-end sm:justify-between"><div><Logo className="h-9 w-auto brightness-0 invert" /><div className="mt-3"><ByFluxBadge className="text-white/45" /></div><p className="mt-4 text-sm text-white/55">L’aide locale, rendue plus simple.</p></div><div className="flex flex-wrap gap-5 text-sm font-semibold text-white/65"><a href="#fonctionnement">Fonctionnement</a><a href="#services">Services</a><a href="#confiance">Confiance</a><a href="#faq">FAQ</a><a href="/contato">Contact</a></div></div></footer></div></MotionConfig>;
}
