/** Centralized brand asset paths (prefer WebP). */
export const BRAND = {
  logoIcon: '/brand/logo-icon.webp',
  registrarConta: '/brand/registrarconta.webp',
  cadeado: '/brand/cadeado.webp',
  heroTools: '/brand/hero-tools.webp',
  clientHomeHero: '/brand/client-home-hero-trust.webp',
  helperHeroBg: '/brand/helper-hero-bg.webp',
  helperHeroRibbon: '/brand/helper-hero-blue-ribbon.webp',
  linkCreditsStoreBg: '/brand/linkcredits-store-background.webp',
  walletIllustration: '/brand/wallet-illustration.webp',
  linkCreditCoin: '/brand/linkcredit-coin-icon.webp',
  linkCreditPopular: '/brand/linkcredit-popular-stack.webp',
  linkCreditPro: '/brand/linkcredit-pro-stack.webp',
  linkCreditPower: '/brand/linkcredit-power-stack.webp',
  tutorialC1: '/brand/tutorial%20c1.png',
  tutorialC2: '/brand/tutorial%20c2.png',
  tutorialC3: '/brand/tutorial%20c3.png',
  tutorialC4: '/brand/tutorial%20c4.png',
  tutorialC5: '/brand/tutorial%20c5.png',
  tutorialC6: '/brand/tutorial%20c6.png',
  tutorialH1: '/brand/tutorial-helper/p1.png',
  tutorialH2: '/brand/tutorial-helper/p2.png',
  tutorialH3: '/brand/tutorial-helper/p3.png',
  tutorialH4: '/brand/tutorial-helper/p4.png',
  tutorialH5: '/brand/tutorial-helper/p5.png',
  tutorialH6: '/brand/tutorial-helper/p6.png',
  tutorialH7: '/brand/tutorial-helper/p7.png',
  tutorialSwipeDedo: '/brand/dedo1.png',
  introVideo: '/brand/intro.mp4',
} as const;
